### ISSUE TITLE
sendmail issue

### ISSUE THREAD

**Issue by xolom** [linuxserver/docker-fail2ban#9]
With the newest release I can't send mails anymore via `sendmail`.
It gives me following error:
```
sendmail: Cannot open mail:25
```

**Reproducable with:** `echo "Subject: sendmail test" | sendmail -v <email@address.com>`

**Arch:** x86-64

**docker-compose.yml:**

```yml
fail2ban:
    container_name: fail2ban
    build:          fail2ban-dockerfile
    hostname:       xxxx
    restart:        always
    depends_on:
      - mysql
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ./fail2ban/config:/config
      - ./fail2ban/run:/var/run/fail2ban
      - /var/log:/var/log:ro
      - ./nextcloud/data/nextcloud.log:/remotelogs/nextcloud/nextcloud.log:ro
      - ./reverse-proxy/var/log/nginx:/remotelogs/reverse-proxy:ro
      - ./shared/fail2ban:/shared/fail2ban
```

**Dockerfile:**

```Dockerfile
FROM linuxserver/fail2ban:latest

RUN sed -i 's/ -vv//g' /etc/s6-overlay/s6-rc.d/svc-fail2ban/run

RUN apk update && apk add --no-cache python3 py3-pip mysql-dev
RUN pip3 install mysql-connector
```
